# This is a stub module. The actual implementation is provided by RV.
#
# Generated from code Copyright (C) 2023  Autodesk, Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

from typing import Any, List, Tuple
from . import rvtypes

def modeStatus(mode: rvtypes.Mode) -> bool: ...
def modeDrawOnEmpty(mode: rvtypes.Mode) -> bool: ...
def modeDrawOnPresentation(mode: rvtypes.Mode) -> bool: ...
def modeName(mode: rvtypes.Mode) -> str: ...
def modeActive(mode: rvtypes.Mode) -> bool: ...
def modeActivate(mode: rvtypes.Mode) -> None: ...
def modeDeactivate(mode: rvtypes.Mode) -> None: ...
def modeRender(mode: rvtypes.Mode, event: Any) -> None: ...
def remotePyEval(event: Any) -> None: ...
def remotePyExec(event: Any) -> None: ...
def globalBindList(bindings: List[Tuple[str, Any, str]]) -> None: ...
def defineDefaultBindings() -> None: ...
def newStateObject() -> rvtypes.State: ...
